export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  content: string[];
  category: string;
  relatedSlugs: string[];
  kind: "blog" | "landing";
}

export function getReadingTime(content: string[]): number {
  const words = content.join(" ").split(/\s+/).length;
  return Math.max(1, Math.ceil(words / 200));
}

export const blogPosts: BlogPost[] = [
  {
    slug: "25-common-interview-questions-in-english",
    title: "25 Common Interview Questions in English (With Sample Answers)",
    description:
      "The most common English interview questions asked by US hiring managers, with sample answers and tips to sound confident and natural.",
    date: "2026-06-04",
    category: "Interviews",
    kind: "blog",
    relatedSlugs: [
      "star-method-interview-answers",
      "interview-vocabulary-for-professionals",
      "how-to-describe-work-experience",
      "how-to-answer-tell-me-about-yourself",
    ],
    content: [
      "\u{1F4D8} Resumen en español: Estas son las 25 preguntas más comunes en entrevistas de trabajo en Estados Unidos. Incluye ejemplos de respuestas y estrategias para profesionistas mexicanos y LATAM que buscan trabajo en empresas estadounidenses. Si te has quedado en blanco durante una entrevista en inglés, esta guía te ayudará a prepararte con respuestas naturales y efectivas.",

      "If you're a Spanish-speaking professional preparing for a job interview in English, you've probably noticed the questions feel different. They're more behavioral. More open-ended. And the pressure of speaking in a second language makes it harder to think on your feet.",
      "This guide covers the 25 most common interview questions asked by US hiring managers, with sample answers and strategies to help you respond naturally — not like you memorized a script.",

      "## 1. Tell Me About Yourself",
      "This is almost always the first question. Keep it professional and structured: past (your experience), present (your current role), future (why you want this job).",
      "**Sample answer:** \"I'm a software engineer with five years of experience building web applications at Mexican tech companies. Currently, I lead a team of four developers, and I'm looking for an opportunity to work with a US-based engineering team where I can contribute my technical skills and continue growing professionally.\"",
      "**Why this works:** It tells a clear career story — past, present, future — and shows ambition without sounding desperate.",

      "## 2. Why Do You Want to Work Here?",
      "Research the company before the interview. Mention something specific about their product, culture, or mission.",
      "**Sample answer:** \"I admire how your company approaches remote collaboration. Your engineering blog posts about distributed teams really resonated with me because I've been working remotely for three years.\"",
      "**Why this works:** It shows genuine research and connects the company's values to your own experience.",

      "## 3. What Are Your Strengths?",
      "Pick a strength relevant to the role and back it up with a specific example.",
      "**Sample answer:** \"My strongest skill is debugging complex systems. Last quarter, I identified and resolved a performance issue that was affecting 20% of our users. I enjoy the detective work of finding root causes.\"",
      "**Why this works:** It names a concrete skill, provides measurable impact, and shows enthusiasm for the work.",

      "## 4. What Are Your Weaknesses?",
      "Be honest, but show self-awareness and active improvement.",
      "**Sample answer:** \"I used to struggle with public speaking in English. I joined a speaking practice group and started preparing presentations for my team. I'm much more comfortable now, but I still make an effort to improve every week.\"",
      "**Why this works:** It's honest, shows proactive improvement, and reframes a weakness as a growth story.",

      "## 5. Tell Me About a Time You Faced a Challenge",
      "Use the STAR method: Situation, Task, Action, Result.",
      "**Sample answer:** \"We had a critical production outage during a holiday weekend. I organized a small team, identified the root cause within two hours, and deployed a fix. We recovered service before the next business day.\"",
      "**Why this works:** Follows STAR precisely — each element is clear, and the result is measurable.",

      "## 6. Where Do You See Yourself in Five Years?",
      "Show ambition that aligns with the company's growth.",
      "**Sample answer:** \"I want to grow into a senior engineering role and eventually lead larger teams. I see this position as a step toward that goal because of the mentorship culture your company promotes.\"",
      "**Why this works:** It connects personal growth goals to what the company specifically offers.",

      "## 7. Why Should We Hire You?",
      "Summarize your unique value in 2–3 sentences.",
      "**Sample answer:** \"I bring strong technical skills, experience working across time zones, and the ability to communicate clearly in English. I've been collaborating with US-based teams for two years and understand the cultural differences in communication.\"",
      "**Why this works:** It highlights the exact value a bilingual LATAM professional brings to a US team.",

      "## 8. Tell Me About a Time You Worked in a Team",
      "Highlight your role and how you contributed to the team's success.",
      "**Sample answer:** \"We were building a new feature under a tight deadline. I volunteered to handle the API integration while my teammate focused on the frontend. We shipped on time and the feature was adopted by 90% of users in the first month.\"",
      "**Why this works:** It shows teamwork, initiative, and ends with a measurable outcome.",

      "## 9. Describe a Time You Had a Conflict With a Coworker",
      "Focus on resolution, not blame.",
      "**Sample answer:** \"A teammate and I disagreed about the architecture for a new service. Instead of arguing, we wrote a quick prototype for both approaches and presented the tradeoffs to the team. We ended up combining elements from both ideas.\"",
      "**Why this works:** It shows maturity — you focused on evidence, not ego, and found a collaborative solution.",

      "## 10. How Do You Handle Pressure?",
      "Give a concrete example of performing under stress.",
      "**Sample answer:** \"I stay calm under pressure by focusing on what I can control. During a major system migration, I broke the work into small tasks and tracked progress daily. The migration completed ahead of schedule.\"",
      "**Why this works:** It demonstrates a system for handling stress and backs it with a real result.",

      "## 11. What Do You Know About Our Company?",
      "Show you've done your homework.",
      "**Sample answer:** \"Your company recently launched a new AI-powered analytics platform. I read the case study about how it helped a client reduce operational costs by 30%.\"",
      "**Why this works:** It proves you researched the company beyond the homepage.",

      "## 12. Why Did You Leave Your Last Job?",
      "Stay positive. Focus on growth, not frustration.",
      "**Sample answer:** \"I learned a lot at my previous company, but I'm ready for a new challenge. I want to work with a more international team and expand my experience.\"",
      "**Why this works:** It's forward-looking and positive — never complain about past employers.",

      "## 13. What Is Your Greatest Accomplishment?",
      "Pick something measurable and impressive.",
      "**Sample answer:** \"I led the migration of our monolithic application to microservices. The project took eight months and involved coordinating with five teams. After the migration, deployment time dropped from hours to minutes.\"",
      "**Why this works:** It's ambitious, quantifiable, and shows leadership across teams.",

      "## 14. How Do You Prioritize Your Work?",
      "Show you have a system.",
      "**Sample answer:** \"I start each day by identifying the most impactful task and doing it first. I use a priority matrix to separate urgent from important tasks.\"",
      "**Why this works:** It shows you have a repeatable, thoughtful system — not just intuition.",

      "## 15. Tell Me About a Time You Made a Mistake",
      "Own it and explain what you learned.",
      "**Sample answer:** \"I once deployed a change without enough testing and it caused a minor outage. Now I always add automated tests before deploying, and I run changes by a teammate for review first.\"",
      "**Why this works:** It takes responsibility and shows the concrete process improvement that followed.",

      "## 16. Are You Comfortable Working in English?",
      "This is a common question for non-native speakers. Be honest but confident.",
      "**Sample answer:** \"Yes, I'm comfortable. I've been working in English daily for two years — writing documentation, attending meetings, and communicating with US colleagues. I still learn new expressions every day, but it doesn't hold me back.\"",
      "**Why this works:** It's honest about ongoing learning while emphasizing that communication is not a barrier.",

      "## 17. What Is Your Communication Style?",
      "Emphasize clarity and adaptability.",
      "**Sample answer:** \"I believe in over-communicating rather than under-communicating. I write clear documentation, confirm understanding after meetings, and I'm not afraid to ask questions when something isn't clear.\"",
      "**Why this works:** It addresses the biggest concern with remote teams — communication gaps — head-on.",

      "## 18. Describe Your Ideal Manager",
      "Focus on what helps you do your best work.",
      "**Sample answer:** \"I work best with managers who provide clear expectations and regular feedback. I appreciate when a manager trusts me to do my work but is available for support when needed.\"",
      "**Why this works:** It's balanced — you want autonomy but also value guidance, which most managers appreciate.",

      "## 19. How Do You Stay Motivated?",
      "Connect motivation to your work.",
      "**Sample answer:** \"I'm motivated by solving real problems. When I see my code improve someone's workflow or fix an issue they've been struggling with, that's what keeps me engaged.\"",
      "**Why this works:** It ties motivation to impact, which is attractive to any employer.",

      "## 20. What Makes You Unique?",
      "Highlight something that genuinely sets you apart.",
      "**Sample answer:** \"I combine strong technical skills with bilingual communication abilities. I can bridge the gap between Spanish-speaking teams and English-speaking stakeholders effectively.\"",
      "**Why this works:** It directly addresses your competitive advantage as a bilingual professional.",

      "## 21. Tell Me About a Time You Had to Learn Something Quickly",
      "Show your learning process.",
      "**Sample answer:** \"I was assigned to a project using a technology I had never worked with. I spent the weekend going through tutorials, built a small prototype, and was productive by Monday.\"",
      "**Why this works:** It shows resourcefulness, initiative, and the ability to ramp up fast.",

      "## 22. Do You Have Any Questions for Us?",
      "Always say yes. Prepare 2–3 thoughtful questions.",
      "**Sample questions:** \"What does a typical first week look like?\", \"How does the team handle code reviews?\", \"What are the biggest challenges the team is facing right now?\"",
      "**Why this works:** Asking questions shows engagement and turns the interview into a two-way conversation.",

      "## 23. How Do You Handle Feedback?",
      "Show openness and growth mindset.",
      "**Sample answer:** \"I welcome feedback. After code reviews, I take notes on what I can improve. I also ask my manager for regular feedback so I don't have to wait for annual reviews.\"",
      "**Why this works:** It shows you actively seek improvement rather than passively accept feedback.",

      "## 24. Describe Your Work Ethic",
      "Use examples from your career.",
      "**Sample answer:** \"I take ownership of my work. When I commit to a deadline, I do everything I can to meet it. If I see something broken, I fix it even if it's not my responsibility.\"",
      "**Why this works:** It shows accountability and initiative beyond your job description.",

      "## 25. What Are Your Salary Expectations?",
      "Research the market rate and give a range.",
      "**Sample answer:** \"Based on my research and experience, I'm looking for a range between X and Y. I'm open to discussing based on the full compensation package.\"",
      "**Why this works:** It shows preparation and flexibility without underselling yourself.",

      "---",
      "This guide is part of our comprehensive [English for Job Interviews](/english-for-job-interviews) resource. For more targeted preparation, check out these related guides:",
      "",
      "- [STAR Method Interview Answers in English](/star-method-interview-answers) — Learn how to structure behavioral responses that US recruiters expect.",
      "- [Interview Vocabulary for Professionals](/interview-vocabulary-for-professionals) — Key phrases to use naturally in your next interview.",
      "- [How to Describe Work Experience in English](/how-to-describe-work-experience) — Talk about your professional background with clarity and confidence.",
      "",
      "If you'd like personalized practice, [book a private tutoring session](/signup) with a native English speaker who specializes in interview preparation for LATAM professionals.",
    ],
  },
  {
    slug: "star-method-interview-answers",
    title: "STAR Method Interview Answers in English",
    description:
      "Learn how to structure behavioral interview answers using Situation, Task, Action, and Result.",
    date: "2026-06-03",
    category: "Interviews",
    kind: "landing",
    relatedSlugs: [
      "25-common-interview-questions-in-english",
      "interview-vocabulary-for-professionals",
      "how-to-describe-work-experience",
      "how-to-answer-tell-me-about-yourself",
    ],
    content: [
      "\u{1F4D8} Resumen en español: El método STAR te ayuda a responder preguntas de comportamiento en entrevistas en inglés con estructura, claridad y resultados concretos. Si te cuesta organizar tus ideas bajo presión, este artículo te da una fórmula simple para sonar profesional y convincente.",
      "Behavioral interview questions are hard because they ask for evidence, not opinions. US hiring managers want to hear about a real situation, the task you owned, the action you took, and the result you delivered.",
      "The STAR method gives you a repeatable structure so you can answer clearly without rambling or freezing.",
      "## 1. Situation",
      "Set the context in one or two sentences. Keep it specific and short.",
      "**Sample answer:** \"Our team was behind schedule on a customer-facing release, and we were getting pressure from sales and support to ship quickly.\"",
      "**Why this works:** It gives the interviewer enough context to understand the stakes without wasting time.",
      "## 2. Task",
      "Explain what you were responsible for. Focus on your role, not the whole company story.",
      "**Sample answer:** \"My task was to coordinate the backend changes, unblock the frontend team, and make sure we still met the deadline.\"",
      "**Why this works:** It shows ownership and makes your contribution easy to identify.",
      "## 3. Action",
      "This is the most important part. Describe what you personally did, step by step.",
      "**Sample answer:** \"I broke the work into smaller milestones, held a short daily check-in with the team, and paired with one developer to solve the API issue that was delaying the launch.\"",
      "**Why this works:** It shows initiative, collaboration, and concrete problem solving.",
      "## 4. Result",
      "End with the outcome. Use numbers if possible.",
      "**Sample answer:** \"We launched two days later than planned, but the release was stable and reduced support tickets by 18% in the first month.\"",
      "**Why this works:** A measurable result makes your answer memorable and credible.",
      "## 5. Common Mistakes",
      "A lot of candidates lose points because they spend too much time on the situation and not enough on the action.",
      "Another mistake is saying what the team did without making your own role clear. If you want the interviewer to remember you, make your contribution easy to follow.",
      "## 6. A Simple Formula",
      "If you get nervous, use this sentence pattern:",
      "**Sample answer:** \"In that situation, I was responsible for X. I did Y and Z. As a result, we achieved A.\"",
      "**Why this works:** It keeps you focused and prevents you from drifting into vague storytelling.",
      "---",
      "If you want more examples, read [25 Common Interview Questions in English](/blog/25-common-interview-questions-in-english) or explore [Interview Vocabulary for Professionals](/interview-vocabulary-for-professionals).",
      "",
      "For live practice, [book a private tutoring session](/signup) and we can turn your own experience into polished STAR answers.",
    ],
  },
  {
    slug: "interview-vocabulary-for-professionals",
    title: "Interview Vocabulary for Professionals",
    description:
      "Key phrases and vocabulary to sound natural, confident, and professional in English interviews.",
    date: "2026-06-02",
    category: "Business English",
    kind: "landing",
    relatedSlugs: [
      "25-common-interview-questions-in-english",
      "star-method-interview-answers",
      "how-to-describe-work-experience",
      "how-to-answer-tell-me-about-yourself",
    ],
    content: [
      "\u{1F4D8} Resumen en español: En una entrevista en inglés, no basta con tener buen nivel. También necesitas vocabulario profesional para describir logros, responsabilidades y fortalezas con naturalidad.",
      "Interview vocabulary is not about using fancy words. It's about using the right words for the right moment so you sound clear, direct, and credible.",
      "## 1. Describing your role",
      "Use verbs and nouns that sound active and professional.",
      "**Useful phrases:** led a team, collaborated with, managed, supported, owned, improved, delivered, streamlined, implemented, analyzed.",
      "**Sample sentence:** \"I led a small team of developers and implemented a new workflow that reduced delays in our release process.\"",
      "## 2. Talking about impact",
      "Hiring managers want to hear results, not just tasks.",
      "**Useful phrases:** increased revenue, reduced errors, improved efficiency, boosted retention, shortened turnaround time, saved hours per week.",
      "**Sample sentence:** \"The change improved efficiency and saved the team about six hours per week.\"",
      "## 3. Discussing teamwork",
      "Use words that show collaboration without sounding vague.",
      "**Useful phrases:** cross-functional team, aligned with stakeholders, coordinated with, partnered with, communicated proactively, resolved blockers.",
      "**Sample sentence:** \"I partnered with the design and product teams to resolve blockers before they affected the launch date.\"",
      "## 4. Explaining challenges",
      "You want to sound calm and practical, not dramatic.",
      "**Useful phrases:** challenge, constraint, bottleneck, tradeoff, root cause, workaround, priority, timeline.",
      "**Sample sentence:** \"The biggest constraint was the timeline, so we focused on the highest-impact tasks first.\"",
      "## 5. Talking about yourself confidently",
      "A strong interview answer is direct and specific.",
      "**Useful phrases:** my background is in, I specialize in, I have experience with, I'm particularly strong at, one area I’ve improved is.",
      "**Sample sentence:** \"My background is in backend development, and I'm particularly strong at diagnosing performance issues.\"",
      "## 6. Phrases that sound natural",
      "These small phrases make your English sound more fluent.",
      "**Useful phrases:** to be honest, in my experience, what I found was, the main takeaway, that said, moving forward, at the end of the day.",
      "**Sample sentence:** \"In my experience, the best results come from clear communication and predictable follow-through.\"",
      "---",
      "Use these phrases as building blocks, not scripts. For practice with real answers, review [STAR Method Interview Answers in English](/star-method-interview-answers) and [How to Describe Work Experience in English](/how-to-describe-work-experience).",
      "",
      "If you want help sounding natural instead of translated, [book a private tutoring session](/signup).",
    ],
  },
  {
    slug: "how-to-describe-work-experience",
    title: "How to Describe Work Experience in English",
    description:
      "Talk about your professional background clearly and confidently during interviews.",
    date: "2026-06-01",
    category: "Business English",
    kind: "landing",
    relatedSlugs: [
      "25-common-interview-questions-in-english",
      "star-method-interview-answers",
      "interview-vocabulary-for-professionals",
      "how-to-answer-tell-me-about-yourself",
    ],
    content: [
      "\u{1F4D8} Resumen en español: Esta guía te enseña a describir tu experiencia laboral en inglés de forma profesional, clara y relevante para entrevistas de trabajo.",
      "A lot of candidates know their resume well in Spanish, but struggle to explain that same experience naturally in English.",
      "The key is not translating word for word. The key is to present your experience as a clear story: what you did, what you used, what changed, and what impact you made.",
      "## 1. Start with your current role",
      "Open with your title, company type, and core responsibility.",
      "**Sample answer:** \"I'm a backend engineer at a fintech company, where I focus on API development and performance improvements.\"",
      "**Why this works:** It gives a quick summary without sounding overprepared.",
      "## 2. Add relevant detail",
      "Choose two or three details that matter for the role you're applying for.",
      "**Sample answer:** \"I work mostly with Node.js and PostgreSQL, and I often collaborate with product managers and frontend engineers to deliver new features.\"",
      "**Why this works:** It sounds practical and directly relevant to the job search.",
      "## 3. Show impact",
      "Don’t just say what you did. Say why it mattered.",
      "**Sample answer:** \"One of my recent projects reduced loading time by 35%, which improved the user experience for our most active customers.\"",
      "**Why this works:** A clear result makes your experience more persuasive.",
      "## 4. Explain your career progression",
      "If you have a few jobs, show growth over time.",
      "**Sample answer:** \"I started as a junior developer, moved into a full-stack role, and now I lead delivery on a small product team.\"",
      "**Why this works:** It shows momentum and responsibility.",
      "## 5. Avoid translation traps",
      "Some Spanish phrases sound unnatural if translated directly.",
      "Instead of saying you 'realized' a project, say you delivered it or completed it. Instead of saying you 'handled' everything, say you managed the process or owned the work.",
      "## 6. Keep it concise",
      "Most interview answers should be 45 to 90 seconds. Enough to sound complete, not so long that the interviewer loses the thread.",
      "**Simple structure:** role -> tools -> collaboration -> result.",
      "---",
      "For more interview practice, read [25 Common Interview Questions in English](/blog/25-common-interview-questions-in-english) and [STAR Method Interview Answers in English](/star-method-interview-answers).",
      "",
      "If you'd like help turning your own background into strong interview answers, [book a private tutoring session](/signup).",
    ],
  },
  {
    slug: "how-to-answer-tell-me-about-yourself",
    title: "How to Answer 'Tell Me About Yourself' in English",
    description:
      "Build a strong opening answer that sounds natural, professional, and easy to follow.",
    date: "2026-05-31",
    category: "Interviews",
    kind: "landing",
    relatedSlugs: [
      "25-common-interview-questions-in-english",
      "star-method-interview-answers",
      "interview-vocabulary-for-professionals",
      "how-to-describe-work-experience",
    ],
    content: [
      "\u{1F4D8} Resumen en español: 'Tell me about yourself' suele ser la primera pregunta de una entrevista en inglés, y también una de las más importantes. Aquí aprenderás a responderla con estructura, confianza y sin memorizar un guion.",
      "This question is not asking for your life story. It is asking for a short professional summary that helps the interviewer understand who you are, what you do, and why you are relevant to the role.",
      "A good answer usually has three parts: past, present, future.",
      "## 1. Past",
      "Briefly explain your background.",
      "**Sample answer:** \"I'm a software engineer with five years of experience building web applications.\"",
      "**Why this works:** It gives context without wasting time.",
      "## 2. Present",
      "Say what you do right now and what you are good at.",
      "**Sample answer:** \"Currently, I work on backend systems and data workflows for a fintech product.\"",
      "**Why this works:** It makes your role concrete and current.",
      "## 3. Future",
      "Explain why you are interested in this opportunity.",
      "**Sample answer:** \"I'm now looking for a role where I can work more closely with a US-based team and keep growing in a product-focused environment.\"",
      "**Why this works:** It gives the interviewer a reason to keep listening.",
      "## 4. Put it together",
      "Keep the full answer to about 45 seconds.",
      "**Sample answer:** \"I'm a software engineer with five years of experience building web applications. Right now I focus on backend systems and data workflows for a fintech product, and I enjoy working on problems where performance and reliability matter. I'm looking for a role where I can collaborate with a US-based team and keep growing in a product-focused environment.\"",
      "**Why this works:** It is clear, professional, and easy for an interviewer to follow.",
      "## 5. What to avoid",
      "Don't start with your childhood, your hobbies, or a long chronological history unless the interviewer asks.",
      "Don't sound like you are reading from a resume. The goal is to sound like a real person with a clear career direction.",
      "---",
      "If you want more examples of strong answers, read [25 Common Interview Questions in English](/blog/25-common-interview-questions-in-english).",
      "",
      "For personalized feedback on your opening answer, [book a private tutoring session](/signup).",
    ],
  },
];
