export const campaignSchemaValidation = {
  $jsonSchema: {
    bsonType: "object",
    required: [
      "code",
      "label",
      "medium",
      "target",
      "active",
      "permanent",
      "scanCount",
      "signupCount",
      "createdAt",
      "updatedAt",
    ],
    additionalProperties: false,
    properties: {
      _id: { bsonType: "objectId" },
      code: { bsonType: "string", minLength: 1, maxLength: 48 },
      label: { bsonType: "string", minLength: 1 },
      medium: { bsonType: "string", minLength: 1 },
      target: { bsonType: "string", minLength: 1 },
      active: { bsonType: "bool" },
      permanent: { bsonType: "bool" },
      fallbackCode: { bsonType: "string", minLength: 1, maxLength: 48 },
      scanCount: { bsonType: "int", minimum: 0 },
      signupCount: { bsonType: "int", minimum: 0 },
      notes: { bsonType: "string" },
      createdAt: { bsonType: "date" },
      updatedAt: { bsonType: "date" },
      deactivatedAt: { bsonType: "date" },
    },
  },
};
